import { images, menu, workshops, money } from '../data/catalog'
import { Image, Heading, VisitCTA } from '../components/UI'
import { cafe } from '../data/cafe'
export default function Home() {
 return <>
 <section className="hero"><Image src={images.cafe} alt="Warm sunlight across a peaceful café and coffee counter" eager /><div className="hero-shade" /><div className="hero-content"><p className="eyebrow">KOREAN-INSPIRED · RAJAGIRIYA, SRI LANKA</p><h1>A little space<br />to <em>slow down.</em></h1><p>A Korean-inspired café and creative space. Thoughtful coffee, hands-on workshops, and gifts with meaning.</p><div className="hero-actions"><a className="button light" href="#menu">View Menu <span aria-hidden="true">↗</span></a><a className="button hero-secondary" href="#workshops">Explore Workshops <span aria-hidden="true">↗</span></a></div></div><div className="hero-caption"><span>GOOD COFFEE. GENTLE MOMENTS.</span><span>SEOUL-INSPIRED · ROOTED IN RAJAGIRIYA</span></div><div className="hero-stamp" aria-hidden="true"><span>A LITTLE WISH</span><b>소원</b><span>A LITTLE JOY</span></div></section>
 <div className="values-strip"><span>Thoughtfully brewed</span><i aria-hidden="true">✳</i><span>Made by you</span><i>✳</i><span>Given with love</span><i>✳</i><span>Enjoyed slowly</span></div>
 <section className="welcome section"><p className="eyebrow">안녕하세요 · WELCOME TO SOWON</p><h2>More than a café.<br />A little feeling of <em>belonging.</em></h2><p>Inspired by the quiet charm of Korean cafés, SOWON is a place to pause in {cafe.location}.<br className="desktop-break" /> Sip something lovely, make something meaningful, and find joy<br className="desktop-break" /> in the simple moments in between.</p><a className="text-link" href="#about">Our little story <span>↗</span></a><span className="welcome-flower" aria-hidden="true">✳</span></section>
 <section className="experience-paths section" aria-label="Three ways to enjoy SOWON">
  <article><p className="eyebrow">01 / SIP</p><h2>Café & Coffee</h2><p>Carefully brewed coffee, comforting flavors, and a favorite seat by the window.</p><a className="text-link" href="#menu">Explore Menu <span aria-hidden="true">↗</span></a></article>
  <article><p className="eyebrow">02 / MAKE</p><h2>Creative Workshops</h2><p>A warm drink, a little guidance, and the quiet pleasure of making something yourself.</p><a className="text-link" href="#workshops">View Workshops <span aria-hidden="true">↗</span></a></article>
  <article><p className="eyebrow">03 / GIVE</p><h2>Custom Gifts</h2><p>A name, a note, a thoughtful detail. Small gifts that feel like they could only come from you.</p><a className="text-link" href="#gifts">Create a Gift <span aria-hidden="true">↗</span></a></article>
 </section><section className="section cafe-section"><Heading eyebrow="SIP SOMETHING LOVELY" title="Your new usual." link="Explore the menu" href="#menu">Comfort in a cup. A little sweetness on the side.</Heading><div className="grid three">{menu.slice(0, 3).map(item => <a href="#menu" className="product-card" key={item.name}><div className="card-photo"><Image src={item.image} alt={item.name} /><span className="badge">{item.tag}</span></div><div className="card-title"><h3>{item.name}</h3><span>{money(item.price)}</span></div><p>{item.description}</p></a>)}</div></section>
 <section className="workshop-home section"><Heading eyebrow="LESS SCROLLING, MORE CREATING" title="Make a little time to make." link="View Workshop Schedule" href="#workshops">No experience needed. Just a little curiosity.</Heading><div className="grid three">{workshops.slice(0, 3).map((item, index) => <a className="workshop-preview" href="#workshops" key={item.name}><Image src={item.image} alt={`${item.type} materials and handmade pieces`} /><div><span className="eyebrow">0{index + 1} / {item.type}</span><h3>{item.name}</h3><p>{item.description}</p><span className="round-arrow" aria-hidden="true">↗</span></div></a>)}</div><p className="workshop-more">A little more to explore <span>Journaling · Flower Arranging · Music Sessions</span></p></section>
 <section className="gift-feature section"><div className="gift-collage"><Image src={images.gifts} alt="Thoughtfully wrapped gifts with ribbon" /><div className="gift-note">little things,<br /><em>big feelings.</em><span>with love, sowon ♡</span></div></div><div className="gift-copy"><p className="eyebrow">FOR SOMEONE, OR FOR YOU</p><h2>A small gift.<br /><em>A lasting feeling.</em></h2><p>A name on a mug. A note tucked into a box. We believe the most meaningful gifts are the ones with a little of you in them.</p><p className="gift-types">Coffee sets · Mugs · Gift boxes · Cards<br />Keepsakes · Plushies · Handmade flowers · Chocolates</p><a className="button" href="#gifts">Create a Gift <span>↗</span></a></div></section>
 <section className="experience"><Image src={images.interior} alt="A welcoming café with warm wood, plants, and shared tables" /><div><p className="eyebrow">THE SOWON WAY OF LIFE</p><h2>Sip. Create. Gift.<br /><em>Slow down.</em></h2><p>Not every moment needs to be a big one.<br />Sometimes, the little things are everything.</p></div></section><VisitCTA />
 </>
}

