import ContactForm from '../components/ContactForm'
import { PageIntro, Image, VisitCTA } from '../components/UI'
import { images } from '../data/catalog'
import { cafe } from '../data/cafe'
export function About() {
 return <><PageIntro eyebrow="소원 · A WISH, A HOPE" title="Our little wish for you.">{cafe.description} Made for a gentler kind of day.</PageIntro><section className="section story"><Image src={images.interior} alt="Sunlit café seating with plants and natural wood" /><div><p className="eyebrow">OUR STORY</p><h2>Good things begin<br />with a little wish.</h2><p>SOWON takes its name from the Korean word for a wish. Ours is simple: to create a space where you can feel a little more present.</p><p>Inspired by neighborhood cafés in Seoul, we imagined a little retreat in Rajagiriya where the coffee is carefully made, the tables welcome a friend, and an afternoon can become something you made with your own hands.</p><p>Stay for a second cup. Try your hand at clay. Wrap something for someone you love. At SOWON, these small rituals bring us closer — to ourselves and to each other.</p></div></section><section className="section philosophy"><div><p className="eyebrow">01 / OUR SPACE</p><h2>Room to simply be.</h2><p>Warm wood, soft light, and a favorite corner. Come with a book, a friend, or no plans at all.</p></div><div><p className="eyebrow">02 / WHY SOWON</p><h2>Little things matter.</h2><p>A cup made with care. A handwritten note. The small details that make an ordinary day feel special.</p></div><div><p className="eyebrow">03 / COFFEE & CREATIVITY</p><h2>Find your own rhythm.</h2><p>We bring thoughtful coffee and gentle creative sessions together. There’s no perfect result to chase, only the pleasure of making.</p></div></section><VisitCTA /></>
}
export function Contact() {
 return <><PageIntro eyebrow="COME AS YOU ARE" title="We’ll put the kettle on.">A question, a little idea, or simply a hello.</PageIntro><section className="section contact-grid"><div><p className="eyebrow">FIND OUR LITTLE CORNER</p><h2>Stay for a while.</h2><dl className="contact-details"><div><dt>Our address</dt><dd>{cafe.location}</dd></div><div><dt>Opening hours</dt><dd>{cafe.openingHours.map(({ days, hours }) => <div key={days}>{days} · {hours}</div>)}</dd></div><div><dt>Say hello</dt><dd><a href={'mailto:' + cafe.email}>{cafe.email}</a><br />{cafe.phone} · Demo contact number</dd></div><div><dt>Little moments, shared</dt><dd><span className="social-placeholder">Instagram · {cafe.instagram}</span><br /><small>Placeholder profile · link coming soon</small></dd></div></dl></div><ContactForm /></section><section className="map-placeholder" aria-label="Illustrative map placeholder"><div className="map-road one" /><div className="map-road two" /><div className="map-road three" /><div className="map-label"><span aria-hidden="true">✳</span><h2>Your next little escape.</h2><p>SOWON Café · {cafe.location}</p><small>Illustrative Rajagiriya map · Portfolio concept, not directions.</small></div></section></>
}
